### ISSUE TITLE
✨[Feature Request]: Add Chatbot for helping donors or recipients to know more about the sharing 

### ISSUE THREAD

**Issue by Saumya-28** [sanika391/SpoonShare#102]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Add Chatbot using Gemini API

### Use Case

for helping donors or recipients to know more about the sharing.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by vishalmaurya850** [comment]
Assign this issue to me

**Comment by vishalmaurya850** [comment]
https://github.com/sanika391/SpoonShare/pull/103#issue-2364793929 Check the Pull Request and running file for AI ChatBot

**Comment by vishalmaurya850** [comment]
Now you should close this issue
