### ISSUE TITLE
📝[Documentation Update]: Enhance Readme.md

### ISSUE THREAD

**Issue by ananyag309** [sanika391/SpoonShare#113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

I am willing to enhance readme.md under gssoc adding feature in section which showcase that the project was part of gssoc, table of content for easy navigation. Moreover add codeofconduct.md, contributing.md lisence.md to main readme.me file. etc

### Suggested Change

i will enhance it by adding feature in section which showcase that the project was part of gssoc, table of content for easy navigation. Moreover add codeofconduct.md, contributing.md lisence.md to main readme.me file. etc

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by sanika391** [comment]
@ananyag309 I'm happy to assign you this issue! Looking forward to seeing your enhancements to the `README.md` and the addition of `codeofconduct.md`, `contributing.md`, and `license.md` sections. Let me know if you have any questions or need further information!

Regards,
Sanika Chavan.
[https://www.linkedin.com/in/sanika-chavan-52457b236]
