### ISSUE TITLE
🪲[Bug]:  UI overflow in dashboard page, recycle page, Donate food page

### ISSUE THREAD

**Issue by Pra-kas** [sanika391/SpoonShare#13]
There is ui overflow in dashboard,recycle and Donate food pages.Please assign me mam @sanika391 . I would like to rectify this issue.

![Screenshot from 2024-05-14 20-07-25](https://github.com/sanika391/SpoonShare/assets/103827847/b2d850e5-e7af-40d6-828d-514554ec9557)
![Screenshot from 2024-05-14 20-06-40](https://github.com/sanika391/SpoonShare/assets/103827847/37e7ee72-7689-4946-a32d-b258ba112cee)
![Screenshot from 2024-05-14 20-06-45](https://github.com/sanika391/SpoonShare/assets/103827847/f69c533e-4d5a-4974-958d-d107a6ab175d)

**Comment by varshithar12** [comment]
I agree to follow this project's Code of Conduct
 I'm a GSSOC'24 contributor
 I want to work on this issue.

**Comment by Pra-kas** [comment]
@sanika391 Mam i have solved ui overflow issues. I have raised pr. Please look in to it mam.

[Screencast from 2024-05-15 17-04-42.webm](https://github.com/sanika391/SpoonShare/assets/103827847/f6d49aae-3dcb-45c1-939d-9b8432248634)

**Comment by VITianLalit** [comment]
Pls, Assign it to me this issue also?? @sanika391

**Comment by sanika391** [comment]
[VITianLalit](https://github.com/VITianLalit)

The issue with the UI overflow on the dashboard page, recycle page, and Donate food page has already been resolved and the PR has been merged. Apologies for not closing the issue sooner. Is there anything else you'd like to work on? Let me know, and I'll be happy to assign it to you.

Thanks,
Sanika Chavan.
[https://www.linkedin.com/in/sanika-chavan-52457b236]
