### ISSUE TITLE
💡[FEATURE]: Header size reduction

### ISSUE THREAD

**Issue by Rags-Mishra** [sanika391/SpoonShare#15]
**Is your feature request related to a problem? Please describe.**
In mobile view the heading is taking up a lot of space which diverts the user attention towards the heading and not the actual content of the site

**Describe the solution you'd like**
A simple reduction of the orange heading would make site appealing to the user

**Additional context**
Here's a screenshot of what it looks like-
![image](https://github.com/sanika391/SpoonShare/assets/83007531/ff3663c3-a3c1-48b8-a8fe-e0355a531fd7)
 
### I would request you to assign this issue to me under GSSOC'24. Thank you!

**Comment by LEARNER-dakshesh** [comment]
Hello @sanika391 can you please assign me this isssue. I wanted to work on issue.

**Comment by sanika391** [comment]
This issue has been resolved. Is their anything else you want to work
upon......
