### ISSUE TITLE
📝[Docs]:  Creation of PULL-REQUEST-TEMPLATE.

### ISSUE THREAD

**Issue by anglerfishlyy** [sanika391/SpoonShare#19]
**What Docs changes are you proposing?**
creating a new one.

**Why do the Docs need this improvement? What is the motivation for this change? How will this change benefit the community?**
There is no pull request template.This template allows/enables contributors to write PRs fastly without wasting much time pondering about what to write and how to start?
 
**Describe the solution you'd like**
CREATE a TEMPLATE for PR.

* This enables PAs,viewers to easily understand a PR as that would be precise,concise and  the point.

Thank You.

**Comment by anglerfishlyy** [comment]
Kindly , assign me  and label its level for this issue .(GSSOC and its level)

**Comment by sanika391** [comment]
Hello!!
For uploading or making changes in the doc their is no level to be mentioned. When you will make specific changes in the code then only it would considered as Level1,2 or 3 task.....

**Comment by anglerfishlyy** [comment]
so , Doesn't it count towards gssoc leaderboard?

**Comment by sanika391** [comment]
It counts but as you already know that for Level 1 you have 15 points,level
2 25
So for gssoc level 5 points aare assigned
