### ISSUE TITLE
BUG: REARRANGEMENT OF UI, The UI of the webapp is arranged un accordingly

### ISSUE THREAD

**Issue by Idiotmonk22** [sanika391/SpoonShare#2]
*This app is a much efficient one among all as it focuses on filling up the empty stomachs, the app's UI is arranged un accordingly 
*The access is blocked while signing in with google 
*No login button is found if i am registering for a new account 
![Screenshot (70)](https://github.com/sanika391/SpoonShare/assets/146474550/862c074f-2ea8-461f-8974-a8d9905a59f6)
![Screenshot (69)](https://github.com/sanika391/SpoonShare/assets/146474550/e184eb8a-f02d-4fd1-92bf-2373db974501)
![Screenshot (68)](https://github.com/sanika391/SpoonShare/assets/146474550/7ac4fa7d-9595-42f2-a423-3b5bcd7274b0)

Please assign this project for me under GSSOC'24 @sanika391

**Comment by xkaper001** [comment]
Hey @sanika391 Please assign this issue to me (A GSSoC'24 Contributor) as it has been a week for the user to whom this issue was assigned seems inactive.

**Comment by sanika391** [comment]
You have not sent me an issue request. Please do sent it

**Comment by Idiotmonk22** [comment]
Mam I'm not feeling well, assign it to somebody else, no problem. I like to
contribute in future

**Comment by sanika391** [comment]
Ok, take care. Get well soon

**Comment by xkaper001** [comment]
@sanika391 you can assign me this issue then

**Comment by sanika391** [comment]
I have done it!!
