### ISSUE TITLE
🪲[Bug]:  Duplicate Page Loads from Multiple Button Clicks

### ISSUE THREAD

**Issue by Pra-kas** [sanika391/SpoonShare#22]
When a user repeatedly clicks a button associated with page navigation, the same page reloads each time, resulting in multiple instances of the same page. This behavior requires the user to navigate back through multiple instances of the page, causing inconvenience. 

[Screencast from 2024-05-15 18-23-18.webm](https://github.com/sanika391/SpoonShare/assets/103827847/40a99588-155d-4e19-969e-593fc7e08f7e)

**Comment by kunal03b** [comment]
Hey!
I have worked on this type of issue in my project. I can handle this issue.
Can you please assign this to me.

**Comment by Pra-kas** [comment]
Mam @sanika391  i have fixed multiple page overloading issue.
I have raised PR.

[Screencast from 2024-05-23 12-30-50.webm](https://github.com/sanika391/SpoonShare/assets/103827847/cda98347-9ad6-4ab4-a098-117bb635a803)

**Comment by shayaanahmad7** [comment]
Hello @sanika391 ma'am ,I want to contribute on this issue , please assign this issue to me!!!

**Comment by sanika391** [comment]
Hi @shayaanahmad7,

Thank you for your enthusiasm and willingness to contribute! However, I wanted to let you know that this issue has already been resolved, and a PR addressing it has been merged recently.

We appreciate your initiative, and we encourage you to check out other open issues where your help might be needed. Your contributions are highly valued, and we look forward to working with you on future improvements.

Best regards,
Sanika Chavan
[https://www.linkedin.com/in/sanika-chavan-52457b236]
