### ISSUE TITLE
Enhance pubspec.yaml: Update Dependencies, Improve Organization

### ISSUE THREAD

**Issue by mdazfar2** [sanika391/SpoonShare#28]
## Description
I'd like to suggest some improvements to the pubspec.yaml file to enhance the project's maintainability and security:

1. **Update Outdated Dependencies:**
  - Consider updating ```cupertino_icons``` to the latest version (`^2.2.1`).
  - Update `firebase_core` and potentially other Firebase packages to their latest null-safe versions (check official documentation for compatibility).

2. **Improve Organization:**
  - Organize dependencies logically by category (e.g., UI, Firebase, Data Storage, etc.) for better readability.

3. **Font Weights:**
  - In the `DM Sans` font definition, change the `weight` property to an integer value (e.g., `weight: 700`).

4. **Web Configuration: (If applicable)**
  - In `flutter_launcher_icons`, replace `"#hexcode"` with the actual hex codes for `background_color` and `theme_color` in the web configuration.

## Additional Notes

**Consider using a linter like `dart_code_metrics` to enforce consistent formatting and catch potential issues.**

## Benefits:
- Improved project maintainability
- Enhanced security through updated dependencies
- Clearer organization for easier future modifications

> I'm eager to contribute and help make this project even more user-friendly!

**Comment by Nandhinirameshmala** [comment]
assign this to me

**Comment by mdazfar2** [comment]
@Nandhinirameshmala This issue is closed. Raise a new issue by taking up this same issue.
