### ISSUE TITLE
Missing CONTRIBUTING.md File in Repository

### ISSUE THREAD

**Issue by suhanipaliwal** [sanika391/SpoonShare#3]
The repository currently lacks a CONTRIBUTING.md file, which is an important resource for guiding potential contributors on how to engage with the project effectively. A CONTRIBUTING.md file outlines the contribution guidelines, coding standards, and procedures for submitting pull requests, thus streamlining the contribution process and ensuring consistency across contributions.

Could you please assign this issue to me under GSSOC 24.

**Comment by Saumya-28** [comment]
Hi @suhanipaliwal !
I have previously worked with quality documentations and written Medium Articles hence I am interested to work on this issue. Could you please assign me this issue?

**Comment by sanika391** [comment]
You have just added code of conduct file. It's documention and not any
coding work.
According to the instructions I have received from above for this I just
have to add gssoc & not Level1,2......

**Comment by varshithar12** [comment]
I agree to follow this project's Code of Conduct
 I'm a GSSOC'24 contributor
 I want to work on this issue.
