### ISSUE TITLE
🪲[Bug]: When any of the fields is wrong, it redirects it to the main page with the error

### ISSUE THREAD

**Issue by Saumya-28** [sanika391/SpoonShare#34]
**Describe the bug**
When any of the fields in the Signup Page is wrong, it redirects it to the main page with the error, which is more complicated for user experience to re-enter everything again.

**To Reproduce**
1. Go to Start Donating 
2. fill in the details and add 12-digit number
3. it will show this error in the main page

**Expected behavior**
It should show the error in the same page and let user change the value without redirecting it to the login page, making the Signup process smoother.

**Screenshots**
<img src="https://github.com/sanika391/SpoonShare/assets/98171392/893216e1-2c23-462c-95af-d93fbf6b7c2d" alt="Filter Option" width="200" height="400">
<img src="https://github.com/sanika391/SpoonShare/assets/98171392/ed0412ea-3fbb-4e2f-a31c-d950384d1ca1" alt="Filter Option" width="200" height="400">

**Smartphone (please complete the following information):**
 - Device: pixel Emulator Api 33
 - OS: Andoid 13

I would like to work on this issue under GSSoC'24.

**Comment by LEARNER-dakshesh** [comment]
Hello @sanika391 can you please assign me this isssue. I wanted to work on issue.

**Comment by sanika391** [comment]
Do send issue then only I am able to assign you with the task

**Comment by sanika391** [comment]
I have assigned it to you. Check it once and let me know.
