### ISSUE TITLE
🪲[Bug]: Render flex error in "Map View Shared Food" screen

### ISSUE THREAD

**Issue by SumitPareek2401** [sanika391/SpoonShare#36]
**Describe the bug**
MapWidget got a render flex error by some pixels on the bottom.

**To Reproduce**
1. Go to 'lib/widgets/maps_widget.dart'
3. Scroll down to 'line no. 231'

**Expected behavior**
The size of the Map Widget should be fixed according to the size of all devices.

**Screenshots**
![s2](https://github.com/sanika391/SpoonShare/assets/122019171/242f3290-049c-4d08-9f20-62b8b78f2024)

fixed:
![s1](https://github.com/sanika391/SpoonShare/assets/122019171/4d055841-df80-4d55-81ba-e14b49ca8860)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by SumitPareek2401** [comment]
@sanika391 Please assign this issue to me.

**Comment by sanika391** [comment]
Ok. I have assigned u the issue

**Comment by sanika391** [comment]
I have assigned you the issue
