### ISSUE TITLE
🪲[Bug]: When navigating through bottom navigation bar, it creates and navigates to a new Scaffold instead of refreshing the existing Scaffold and also has some UI Issues.

### ISSUE THREAD

**Issue by ascoder1109** [sanika391/SpoonShare#38]
**Describe the bug**
When navigating through bottom navigation bar, the screen navigates and creates a new screen instead of remaining in same screen and refreshing it, also some parts of the app has UI issues. 

**To Reproduce**
1. Go to main.dart
2. home: const DashboardHomePage(role: "NGO")

**Expected behavior**
1. The Scaffold should remain same and refreshed when navigating to bottom navigation bar (similar to navigating through bottom navigation bar in WhatsApp).

**Screenshots**
From this:
https://github.com/sanika391/SpoonShare/assets/100013000/ca5701d5-a1b8-45e8-896f-833e4dbeb0dc

I want to create something like this:

https://github.com/sanika391/SpoonShare/assets/100013000/ab1bb33a-689b-4864-822b-971fd4f6867d

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy M33 5G
 - OS: Android 14

**Additional context**
Please Assign me this issue so I can work on it.

**Comment by ascoder1109** [comment]
@sanika391 Please Assign me this issue so I can work on it.

**Comment by sanika391** [comment]
I have did it do check it once

**Comment by ascoder1109** [comment]
OK I have checked

**Comment by sanika391** [comment]
Great work keep it up. If you find any other issues do work on it. Great to
connect with you..
