### ISSUE TITLE
Add Code of conduct file

### ISSUE THREAD

**Issue by suhanipaliwal** [sanika391/SpoonShare#4]
I would like to add the code of conduct file in the repository which is currently missing.

**Comment by Shubham-Zone** [comment]
i would like to contribute to this issue... kindly assign me i am GSSOC'24 contributor

**Comment by Saumya-28** [comment]
Hi @suhanipaliwal !
I have previously worked with quality documentations and written Medium Articles hence I am interested to work on this issue. Could you please assign me this issue?

**Comment by hammad-16** [comment]
Hello @suhanipaliwal 
I am a GSSOC'24 contributor and I have good experience of writing articles and documentations for different platforms, making sure of appropriate indentations, vocabulary usage and an efficient understandability. I request you to please assign me this issue.

**Comment by suhanipaliwal** [comment]
Could you please add the labels of GSSOC'24 and the label of appropriate level like level 1, 2 or 3.
