### ISSUE TITLE
💡[FEATURE]: Create Issue forms and make the issue options more visually appealing 

### ISSUE THREAD

**Issue by TonyStark-47** [sanika391/SpoonShare#44]
**Is your feature request related to a problem? Please describe.**
- Currently, there is an issue template for this repo, but no issue form which will help users in contributing.

**Describe the solution you'd like**
- I will add Issue Forms to the respective issues to make it easier for the contributor to raise it.
Here is an example of how a Bug Issue Form will look like 👇

![image](https://github.com/sanika391/SpoonShare/assets/73957207/9d26d32b-cdc9-4990-a9bf-8af805d93d8d)

**Comment by TonyStark-47** [comment]
I want to work on this issue. So, kindly assign this issue to me ( GSSOC'24 ).

**Comment by TonyStark-47** [comment]
Hey, @sanika391, I raised a PR #45 related to this issue. Please check it out.

**Comment by sanika391** [comment]
[TonyStark-47](https://github.com/TonyStark-47) Sure I would just go through it.

**Comment by sanika391** [comment]
Just a friendly remainder please star the repository as its must for moving ahead and merging the pull request.

**Comment by TonyStark-47** [comment]
Yes, I already did it.

**Comment by sanika391** [comment]
I have seen that you have not started the repository yet and have merged
it. Please do the needful!!

**Comment by TonyStark-47** [comment]
Hey @sanika391, look at this screenshot, I have already starred the repo:

![image](https://github.com/sanika391/SpoonShare/assets/73957207/3ca8bfa7-e031-4bc1-bfda-1cd0179fc295)

**Comment by sanika391** [comment]
Hey @Tony Stark,

Sorry for the inconvenience. I've looked at the screenshot, and I can see
that you've already starred the repo. Thank you for your support!

Best regards,
Sanika Chavan
[https://www.linkedin.com/in/sanika-chavan-52457b236]
