### ISSUE TITLE
✨[Feature Request]: Auto Commenting Feat for Issue Creation

### ISSUE THREAD

**Issue by Asymtode712** [sanika391/SpoonShare#48]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like an automated feature that posts a predefined comment on an issue as soon as it is created. This comment could include acknowledgment of the issue, guidelines for further steps, or any other relevant information. The automation should be customizable to accommodate different project workflows and communication styles.

### Use Case

This feature aims to address the problem of delayed and inconsistent communication following the creation of issues. By automatically commenting on issues as soon as they are created, it ensures that contributors receive immediate feedback and acknowledgment for their efforts. This fosters a positive and supportive environment for collaboration, encouraging continued participation and engagement from contributors.

### Add ScreenShots

![issue creation](https://github.com/sanika391/SpoonShare/assets/115717746/d4d296f5-b4ee-4043-ae54-c605aa070ffa)

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by sanika391** [comment]
[Asymtode712](https://github.com/Asymtode712)
I have assigned this issue to you as well. These auto-commenting features will greatly enhance our communication process and contributor engagement. It's great to see your initiative in identifying and working on these improvements. If there are any other areas you are interested in or any additional features you would like to propose, feel free to let me know. Looking forward to your contributions!

**Comment by Asymtode712** [comment]
@sanika391 Before merging the workflow PRs please carry out the following steps so that the workflows can run properly:

**Step 1: Create a Personal Access Token (PAT) with repo Permission**


**1. Navigate to Settings:**

 - Click on your profile picture in the upper-right corner of the page.
 - Select "Settings" from the dropdown menu.

**2. Go to Developer Settings:**

- In the left sidebar, scroll down and click on "Developer settings."

**3. Create a New Token:**

- Click on "Personal access tokens -> Token (classic)" in the left sidebar.
- Click on the "Generate new token" button.

**4. Configure the Token:**

- Token Description: Enter a descriptive name for the token (e.g., Repo Access Token).
- Expiration: Set no expiration.
- Select Scopes: Check the box next to repo to grant full control of private repositories.

**5. Generate Token:**

- Scroll down and click on the "Generate token" button.
- Important: Copy the token to a secure location. You will not be able to see it again once you navigate away from the page.
<br>

**Step 2: Assign the Token to GITHUB_TOKEN Environment Variable**

**1. Navigate to Your Repository:**

- Go to your repository on GitHub.
- Click on the "Settings" tab.

**2. Go to Secrets:**

- In the left sidebar, click on "Secrets and variables" and then "Actions".

**3. Create a New Secret:**

- Click on the "New repository secret" button.
- Name: Enter GITHUB_TOKEN.
- Value: Paste your generated token.
- Click on the "Add secret" button.

**Comment by Asymtode712** [comment]
@sanika391 the above steps are essential for some workflows' functioning
