### ISSUE TITLE
Texts Alignment and Clickable items pointer to be changed from cursor to pointer 

### ISSUE THREAD

**Issue by Deepanshdevelop0** [sanika391/SpoonShare#5]

**Comment by Deepanshdevelop0** [comment]
@sanika391 I want to work on these enhancements without disturbing any pre alignments, please assign me this task to let me complete. Kindly also label this as Gssoc'24.

Thanks

**Comment by Shubham-Zone** [comment]
@sanika391 assign this to me i have 2+ years of experience in flutter i am GSSOC'24 contributor

**Comment by LEARNER-dakshesh** [comment]
Hello @sanika391 can you please assign me this isssue. I wanted to work on issue.

**Comment by sanika391** [comment]
Have you send an issue regarding it??
