### ISSUE TITLE
✨[Feature Request]: Auto Commenting feature for PR Merged

### ISSUE THREAD

**Issue by Asymtode712** [sanika391/SpoonShare#50]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

To enhance our communication and acknowledgment process, we're implementing an auto-commenting feature for specific events within our project repository. This feature will automatically generate comments under the following circumstances:
PR Merged: Upon the successful merging of a pull request (PR), an auto-comment will be added to the corresponding issue, indicating that the PR has been merged and expressing gratitude to the contributor for their valuable contribution.

### Use Case

This feature aims to solve the problem of inconsistent and delayed communication following the merging of PRs. By automating the commenting process, it ensures that contributors receive timely feedback and acknowledgments. It also reduces the administrative burden on maintainers, allowing them to focus more on code reviews and other critical tasks.

### Add ScreenShots

![PR merged](https://github.com/sanika391/SpoonShare/assets/115717746/d4676a7f-809d-4e77-82a6-952eb6b576da)

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Asymtode712** [comment]
@sanika391 please assign me this issue

**Comment by sanika391** [comment]
[Asymtode712](https://github.com/Asymtode712)
I have assigned this issue to you. This feature will be really helpful in maintaining timely and consistent communication within  repository. Great work on identifying this need! If you need any assistance, feel free to reach out. Looking forward to your contribution!
