### ISSUE TITLE
ui over flowing on sign up screen and unable to login due to error related to firebase

### ISSUE THREAD

**Issue by khush1yaaar** [sanika391/SpoonShare#6]
![Screenshot_20240511_234008 1](https://github.com/sanika391/SpoonShare/assets/128786949/f9f3eea1-7e8d-4465-b844-356441dfbb10)
![Screenshot_20240512_200150 1](https://github.com/sanika391/SpoonShare/assets/128786949/b9ce02fb-8c45-4e00-b958-2a01768bf9c0)

**Comment by khush1yaaar** [comment]
please assign me this issue.

**Comment by khush1yaaar** [comment]
please assign it to me. I'm a GSSoC contributor

**Comment by SumitPareek2401** [comment]
It's been 5 days with no updates from the assignee. @sanika391 Could you please assign this issue to me?

**Comment by sanika391** [comment]
[khush1yaaar](https://github.com/khush1yaaar) As I have not received any updates from your side I am assigning this issue to another contributor. But you also do try it. If you need any help do mention or contact.

**Comment by sanika391** [comment]
I have done it....

**Comment by niketpatel-0208** [comment]
Hello. I am a GSSoC contributor. Could you please assign the issue to me?

**Comment by Saumya-28** [comment]
Hi @sanika391 !
Is this issue fixed? as i still get the same error.

**Comment by sanika391** [comment]
[Saumya-28](https://github.com/Saumya-28) Hello Saumya...
This issue has not been fixed yet.

**Comment by sanika391** [comment]
Hello.....
No this issue has not been fixed yet. If you want you can definitely work
on it
