### ISSUE TITLE
🐞[Bug]: Ui overflow in Dashboard and Donate page.

### ISSUE THREAD

**Issue by Pra-kas** [sanika391/SpoonShare#61]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Pixel overflow in two pages.

### Add ScreenShots

![bug1](https://github.com/sanika391/SpoonShare/assets/103827847/5f552d06-20ae-4725-901c-b74d5bfb125c)
![bug2](https://github.com/sanika391/SpoonShare/assets/103827847/6191c03f-16ea-4903-9e2b-1dc45ecdc0ef)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by harsh6045** [comment]
I am also interested in making changes on UI and improving the code quality. I am a GSSOC's 24 Contributor I have an experience in flutter. @sanika391

**Comment by Pra-kas** [comment]
@sanika391  Mam I have resolved UI overflow issues mam.I have raised PR.

![out1](https://github.com/sanika391/SpoonShare/assets/103827847/5585994a-f167-4d94-b616-e9fc00d4a9fb)
![out2](https://github.com/sanika391/SpoonShare/assets/103827847/198a2406-38d5-4d22-b3a7-1a5f05db1278)

**Comment by SETAN747** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Describe the bug
> Pixel overflow in two pages.
> 
> ### Expected behavior
> ### Add ScreenShots
> ![bug1](https://private-user-images.githubusercontent.com/103827847/333184999-5f552d06-20ae-4725-901c-b74d5bfb125c.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MjU0MDcsIm5iZiI6MTcxNjgyNTEwNywicGF0aCI6Ii8xMDM4Mjc4NDcvMzMzMTg0OTk5LTVmNTUyZDA2LTIwYWUtNDcyNS05MDFjLWI3NGQ1YmZiMTI1Yy5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjdUMTU1MTQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGUzNGI1OTdiZTg5ZTE2MThkNmMzMWM3ODg2MTA1ODZiNjE2YWI5YjM3NzEwMDUwOGNiMjM3MmY5NmE0OTZiNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-aLjZeRFHbrs3c2cKWC7QNH0-xHOz1yxZ2j4I_Y-tl0) ![bug2](https://private-user-images.githubusercontent.com/103827847/333185021-6191c03f-16ea-4903-9e2b-1dc45ecdc0ef.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MjU0MDcsIm5iZiI6MTcxNjgyNTEwNywicGF0aCI6Ii8xMDM4Mjc4NDcvMzMzMTg1MDIxLTYxOTFjMDNmLTE2ZWEtNDkwMy05ZTJiLTFkYzQ1ZWNkYzBlZi5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjdUMTU1MTQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzgxMWJiYzkxOGNjZWJhYmQyMDExNDc5MjczMTZhM2JhMjQyMDQzNmM2NzA3NWM5Zjg1NjgwM2FlMzI5OThmZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Nj7DpSgUnBRPjdcZG78VzcDK75UFW9q3Ms1cZmlYd1E)
> 
> ### What browsers are you seeing the problem on?
> _No response_
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

@sanika391 mam can you please assign this issue to me ?

**Comment by sanika391** [comment]
Hi @SETAN747,

Thank you for your attention to the pixel overflow issues. However, I wanted to let you know that this issue has already been resolved and merged as per PR #65. If you encounter any further issues or have other improvements in mind, feel free to reach out or open a new issue.

Thank you for your understanding and continued contributions!

Best regards,
Sanika Chavan
[https://www.linkedin.com/in/sanika-chavan-52457b236]
