### ISSUE TITLE
Want to add a issue template 

### ISSUE THREAD

**Issue by AnitSarkar123** [sanika391/SpoonShare#7]
Please assign me under GSSOC'24

**Comment by Shubham-Zone** [comment]
@sanika391  please assign this to me i have 2+ years of experience and flutter and i am GSSOC'24 contributor

**Comment by officeneerajsaini** [comment]
@sanika391  , I'd like to work on this issue under GSSOC. Could you please add the necessary label and tag to the issue and assign it to me?
