### ISSUE TITLE
Auto comment on opened PR and merged or closed PR 

### ISSUE THREAD

**Issue by MohanRamSridhar** [sanika391/SpoonShare#70]
I'll create a workflow that will auto comment on an opened PR and will also auto comment if the PR is merged or if the PR is closed. This will be helpful for the user to navigate further.
This will also make the work of PA easy.

**Comment by MohanRamSridhar** [comment]
please assign this issue to me under gssoc

**Comment by sanika391** [comment]
Hi @MohanRamSridhar,

Thank you for taking the initiative on this! I have assigned this issue to you under GSSOC. It's great to connect and collaborate with you on creating a workflow to auto-comment on opened, merged, or closed PRs. This will certainly enhance the user experience and streamline the process for project maintainers.

If you need any assistance or have any questions along the way, feel free to reach out. Looking forward to seeing your contributions!

Best regards,
Sanika
[https://www.linkedin.com/in/sanika-chavan-52457b236]
