### ISSUE TITLE
🐞[Bug]: forget password not below the password secrtion

### ISSUE THREAD

**Issue by Ratangulati** [sanika391/SpoonShare#80]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

the forgot password is showing on the right side of the screen.

### Expected behavior

It should be shown below the input box but it is showing on the side of the screen.

### Add ScreenShots

![Screenshot 2024-06-01 at 1 27 28 PM](https://github.com/sanika391/SpoonShare/assets/116749593/9e6dcc06-ef21-469e-be76-dd7854d2376c)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

I would like to work on this issue.

**Comment by nitin-787** [comment]
please assign this issue to me @sanika391
