### ISSUE TITLE
Evaluate Photos of Food Before Uploading in "Share Free Food," "Donate Food," and "Recycle Food" Pages

### ISSUE THREAD

**Issue by igopi77** [sanika391/SpoonShare#90]
**Description:**

There is a need to implement a photo evaluation feature for the "Share Free Food," "Donate Food," and "Recycle Food" pages in the SpoonShare app. The purpose of this feature is to ensure that photos of food, when uploaded from the gallery, are taken within the last 30-40 minutes to maintain freshness and relevance.

**Implementation Approach:**

- In Flutter, the EXIF package will be used to extract the timestamp metadata from the uploaded photos to evaluate their recency.

**Expected Behavior:**

1. Users should be able to upload photos of food in the "Share Free Food," "Donate Food," and "Recycle Food" pages.
2. The app should evaluate the timestamp of the photos uploaded from the gallery.
3. Only photos taken within the last 30-40 minutes should be accepted for upload.
4. Users should receive a clear notification if their photo does not meet the criteria, prompting them to take a new photo or select a recent one.

**Steps to Implement:**

--> EXIF Metadata Extraction:

1. Use the EXIF package in Flutter to extract the timestamp metadata from the uploaded photos.
2. Compare the extracted timestamp with the current time to determine if the photo falls within the 30-40 minute window.

**Video**

https://github.com/sanika391/SpoonShare/assets/123234840/ead48401-d9da-4d30-bb08-46f56b23f4bd

This may be a old photo. so we have to evaluate a photo when it's taken.

**Comment by igopi77** [comment]
@sanika391 Assign this issue to me mam.

**Comment by sanika391** [comment]
Happy to assign this issue to you, @igopi77! Thank you for taking this on. Looking forward to seeing your implementation.

Regards,
Sanika Chavan
[https://www.linkedin.com/in/sanika-chavan-52457b236]

**Comment by igopi77** [comment]
@sanika391 I have completed this issue mam. You can please verify it and merge it mam.
