### ISSUE TITLE
✨[Feature Request]: Create DockerFile for the project

### ISSUE THREAD

**Issue by Ratangulati** [sanika391/SpoonShare#93]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Docker is a must for open-source projects nowadays as it has its own benefits.

### Use Case

Dockerfile has a lot of benefits but consistency and isolation standout the most.

Docker allows you to package your entire application, including its dependencies, into a single container. That makes sure your application will run across different environments.
another benefit of it is it runs in its own environment without interfering with other applications or the host system.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by sanika391** [comment]
Thank you for suggesting this feature, @Ratangulati. Docker support will greatly enhance the consistency and isolation of our application. Looking forward to your implementation. If you need any help, feel free to reach out.

Best,
Sanika Chavan
[https://www.linkedin.com/in/sanika-chavan-52457b236]
